// TrucoPro AR - app.js
// Versión producción separada para GitHub Pages / Cloudflare Pages.
// Archivo generado desde la versión final premium total.

const $ = id => document.getElementById(id);
const pages = [...document.querySelectorAll('.page')];
const navBtns = [...document.querySelectorAll('.nav button')];
navBtns.forEach(b=>b.addEventListener('click',()=>goPage(b.dataset.page)));
function goPage(id){ pages.forEach(p=>p.classList.toggle('active', p.id===id)); navBtns.forEach(b=>b.classList.toggle('active', b.dataset.page===id)); window.scrollTo({top:0,behavior:'smooth'}); }
function toast(msg){ const t=$('toast'); t.textContent=msg; t.classList.add('show'); clearTimeout(t._h); t._h=setTimeout(()=>t.classList.remove('show'),2200); }
function popupPoints(title,line,sub){ $('floatTitle').textContent=title; $('floatLine').textContent=line; $('floatSub').textContent=sub; const f=$('floatScore'); f.classList.add('show'); clearTimeout(f._h); f._h=setTimeout(()=>f.classList.remove('show'),2200); }
function setToggle(node,on){ node.classList.toggle('on', !!on); }

const SUITS = {espada:{name:'espadas', color:'#2d89d5'}, basto:{name:'bastos', color:'#3aa34d'}, oro:{name:'oros', color:'#d7a21d'}, copa:{name:'copas', color:'#c64747'}};
const RANK = {'1-espada':14,'1-basto':13,'7-espada':12,'7-oro':11,'3-espada':10,'3-basto':10,'3-oro':10,'3-copa':10,'2-espada':9,'2-basto':9,'2-oro':9,'2-copa':9,'1-oro':8,'1-copa':8,'12-espada':7,'12-basto':7,'12-oro':7,'12-copa':7,'11-espada':6,'11-basto':6,'11-oro':6,'11-copa':6,'10-espada':5,'10-basto':5,'10-oro':5,'10-copa':5,'7-basto':4,'7-copa':4,'6-espada':3,'6-basto':3,'6-oro':3,'6-copa':3,'5-espada':2,'5-basto':2,'5-oro':2,'5-copa':2,'4-espada':1,'4-basto':1,'4-oro':1,'4-copa':1};
const state = {gameTo:15, flor:false, sound:true, p:0, c:0, handNo:0, mano:'player', turn:'player', ph:[], ch:[], rounds:[null,null,null], ri:0, waiting:false, envidoUsed:false, florUsed:false, trucoValue:1, over:false, seconds:29, timer:null};

function suitSVG(s,size=24){
  if(s==='oro') return `<svg width="${size}" height="${size}" viewBox="0 0 100 100"><circle cx="50" cy="50" r="31" fill="#f2cf58" stroke="#b78314" stroke-width="6"/><circle cx="50" cy="50" r="17" fill="#fff1a8" stroke="#b78314" stroke-width="4"/></svg>`;
  if(s==='espada') return `<svg width="${size}" height="${size}" viewBox="0 0 100 100"><path d="M49 10 L60 40 L53 40 L53 78 L47 78 L47 40 L40 40 Z" fill="#2d89d5" stroke="#1d649f" stroke-width="3"/><path d="M39 77 H61" stroke="#c99e4f" stroke-width="6" stroke-linecap="round"/><path d="M50 78 L50 92" stroke="#7f5b28" stroke-width="5" stroke-linecap="round"/></svg>`;
  if(s==='basto') return `<svg width="${size}" height="${size}" viewBox="0 0 100 100"><path d="M50 12 C61 18,66 29,63 40 C59 58,55 66,52 84" fill="none" stroke="#2f8c42" stroke-width="10" stroke-linecap="round"/><path d="M43 23 C28 26,20 36,24 48 C28 58,37 58,47 53" fill="#58bf6d" stroke="#2f8c42" stroke-width="4"/><path d="M57 34 C72 36,80 46,76 58 C73 68,62 68,54 63" fill="#58bf6d" stroke="#2f8c42" stroke-width="4"/></svg>`;
  return `<svg width="${size}" height="${size}" viewBox="0 0 100 100"><path d="M50 15 C61 22,67 36,63 52 C60 67,50 79,50 79 C50 79,40 67,37 52 C33 36,39 22,50 15 Z" fill="#d44a4a" stroke="#a93131" stroke-width="4"/><path d="M44 64 H56" stroke="#85521d" stroke-width="5" stroke-linecap="round"/></svg>`;
}
function cardName(n,s){ const sp={'1-espada':'Ancho de Espadas','1-basto':'Ancho de Bastos','7-espada':'Siete de Espadas','7-oro':'Siete de Oros'}; return sp[`${n}-${s}`] || `${n} de ${SUITS[s].name}`; }

function figureSVG(kind,s){
  const accent=SUITS[s].color;
  if(kind==='sota') return `<svg width="100" height="112" viewBox="0 0 100 112"><circle cx="50" cy="15" r="10" fill="#f1d6bc" stroke="#6f4723" stroke-width="2"/><path d="M32 30 Q50 21 68 30 L64 90 Q50 100 36 90 Z" fill="#cb403a" stroke="#7b2723" stroke-width="2"/><path d="M24 40 L34 34 L36 62 L27 66 Z" fill="#e9c44d" stroke="#8d6916" stroke-width="2"/><path d="M76 40 L66 34 L64 62 L73 66 Z" fill="#e9c44d" stroke="#8d6916" stroke-width="2"/><path d="M50 30 L50 88" stroke="#6a4c2e" stroke-width="6" stroke-linecap="round"/><path d="M38 73 H62" stroke="#d2b06a" stroke-width="6" stroke-linecap="round"/><path d="M41 14 L46 7 L50 12 L54 7 L59 14" fill="#f0c94c" stroke="#8d6916" stroke-width="2"/><path d="M39 40 Q50 33 61 40" fill="none" stroke="${accent}" stroke-width="4.5"/></svg>`;
  if(kind==='caballo') return `<svg width="110" height="112" viewBox="0 0 110 112"><path d="M20 80 Q20 61 36 52 L50 46 Q62 37 73 42 Q87 48 86 61 L79 64 L77 77 L70 96 L61 96 L58 80 L44 80 L41 96 L33 96 L31 78 L22 80 Z" fill="#9d6b45" stroke="#603f27" stroke-width="2"/><circle cx="60" cy="16" r="9" fill="#f1d6bc" stroke="#6f4723" stroke-width="2"/><path d="M50 27 Q60 19 70 27 L72 64 L50 64 Z" fill="#ecc340" stroke="#906610" stroke-width="2"/><path d="M35 51 Q32 39 43 29" stroke="#603f27" stroke-width="3" fill="none"/><path d="M68 36 L82 32" stroke="#603f27" stroke-width="2"/><path d="M55 16 Q61 10 67 16" fill="none" stroke="${accent}" stroke-width="4"/></svg>`;
  return `<svg width="100" height="112" viewBox="0 0 100 112"><circle cx="50" cy="15" r="10" fill="#f1d6bc" stroke="#6f4723" stroke-width="2"/><path d="M32 31 Q50 21 68 31 L64 92 Q50 102 36 92 Z" fill="#2e74d8" stroke="#22518f" stroke-width="2"/><path d="M24 40 L34 34 L36 64 L27 68 Z" fill="#e6d6aa" stroke="#9b7d36" stroke-width="2"/><path d="M76 40 L66 34 L64 64 L73 68 Z" fill="#e6d6aa" stroke="#9b7d36" stroke-width="2"/><path d="M50 30 L50 90" stroke="#6a4c2e" stroke-width="6" stroke-linecap="round"/><path d="M41 15 L45 8 L50 12 L55 8 L59 15" fill="#f0c94c" stroke="#906610" stroke-width="2"/><path d="M39 40 Q50 33 61 40" fill="none" stroke="${accent}" stroke-width="4.5"/></svg>`;
}

function renderPips(card){
  if([10,11,12].includes(card.n)){
    const title=card.n===10?'SOTA':card.n===11?'CABALLO':'REY';
    const kind=card.n===10?'sota':card.n===11?'caballo':'rey';
    return `<div class="court"><div class="tt">${title}</div>${figureSVG(kind,card.s)}<div class="sub">${suitSVG(card.s,18)} ${SUITS[card.s].name} ${suitSVG(card.s,18)}</div></div>`;
  }
  const patterns={
    1:[[50,50]],
    2:[[35,30],[65,70]],
    3:[[35,24],[50,50],[65,76]],
    4:[[35,28],[65,28],[35,72],[65,72]],
    5:[[35,25],[65,25],[50,50],[35,75],[65,75]],
    6:[[35,20],[65,20],[35,50],[65,50],[35,80],[65,80]],
    7:[[35,18],[65,18],[35,40],[65,40],[50,55],[35,82],[65,82]]
  }[card.n] || [[50,50]];
  return `<div class="pip-grid">${patterns.map(([x,y])=>`<span class="pip" style="left:${x}%;top:${y}%">${suitSVG(card.s,30)}</span>`).join('')}</div>`;
}

function cardHTML(card){ const icon=suitSVG(card.s,17); return `<div class="truco-card"><div class="corner">${card.n}<span class="icon">${icon}</span></div><div class="corner br">${card.n}<span class="icon">${icon}</span></div><div class="art">${renderPips(card)}</div><div class="label">${card.name}</div></div>`; }
function buildDeck(){ const nums=[1,2,3,4,5,6,7,10,11,12]; const d=[]; ['espada','basto','oro','copa'].forEach(s=>nums.forEach(n=>d.push({n,s,id:`${n}-${s}`,r:RANK[`${n}-${s}`],name:cardName(n,s)}))); return d.sort(()=>Math.random()-.5); }
function envidoVal(c){ return c.n>=10?0:c.n; }
function calcEnvido(hand){ const by={}; hand.forEach(c=>{ (by[c.s] ||= []).push(envidoVal(c)); }); let best=0; Object.values(by).forEach(v=>{ v.sort((a,b)=>b-a); if(v.length>=2) best=Math.max(best,20+v[0]+v[1]); else best=Math.max(best,v[0]); }); return best; }
function hasFlor(hand){ return new Set(hand.map(c=>c.s)).size===1; }
function calcFlor(hand){ return 20 + hand.reduce((a,c)=>a+envidoVal(c),0); }

function updateScore(){
  $('scoreP').textContent=state.p; $('scoreC').textContent=state.c; $('topP').textContent=state.p; $('topC').textContent=state.c; $('topTo').textContent=state.gameTo; $('gameToText').textContent=`${state.gameTo} puntos`; $('rulesText').textContent=`${state.flor?'Flor ON':'Flor OFF'} · ${state.sound?'sonido ON':'sonido OFF'}`; $('envidoText').textContent=`Envido: ${calcEnvido(state.ph)||0}${state.flor&&hasFlor(state.ph)?' · Flor disponible':''}`; $('manoPill').textContent=`${state.mano==='player'?'👋 VOS':'🤖 RIVAL'} · ${state.handNo}° (MANO)`; $('turnText').textContent=state.turn==='player'?`TU JUGADA · ${state.seconds}s`:'JUEGA RIVAL'; }
function renderCPU(){ $('cpuBacks').innerHTML = Array.from({length:state.ch.length}).map(()=>'<div class="backcard"></div>').join(''); }
function renderHand(){ $('playerHand').innerHTML = state.ph.map((c,i)=>`<button class="hand-btn" ${state.turn!=='player'||state.waiting||state.over?'disabled':''} onclick="playCard(${i})">${cardHTML(c)}</button>`).join(''); }
function renderSlots(){ for(let i=0;i<3;i++){ const slot=$('slot'+i); slot.className='slot'; slot.innerHTML=''; const r=state.rounds[i]; if(!r) continue; if(r.winner==='player') slot.classList.add('winP'); if(r.winner==='cpu') slot.classList.add('winC'); if(r.cpu){ const d=document.createElement('div'); d.className='mini cpu'; d.innerHTML=cardHTML(r.cpu); slot.appendChild(d);} if(r.player){ const d=document.createElement('div'); d.className='mini player'; d.innerHTML=cardHTML(r.player); slot.appendChild(d);} } }
function renderAll(){ updateScore(); renderCPU(); renderHand(); renderSlots(); updateButtons(); setToggle($('toggleFlor'),state.flor); setToggle($('toggleSound'),state.sound); $('selectPoints').value=String(state.gameTo); }
function updateButtons(){ const lock=state.turn!=='player'||state.waiting||state.over; const envLock=lock||state.envidoUsed||state.ri>0; $('btnTruco').disabled=lock||state.trucoValue>1; $('btnEnvido').disabled=envLock; $('btnReal').disabled=envLock; $('btnFalta').disabled=envLock; $('btnFlor').disabled=!state.flor||!hasFlor(state.ph)||state.florUsed||state.ri>0||lock; }
function log(msg,who='Sistema'){ const d=document.createElement('div'); d.innerHTML=`<b>${who}:</b> ${msg}`; $('gameLog').prepend(d); }
function clearLog(){ $('gameLog').innerHTML=''; }

let audioCtx=null, voice=null;
function unlockAudio(){ try{ if(!audioCtx) audioCtx=new (window.AudioContext||window.webkitAudioContext)(); if(audioCtx.state==='suspended') audioCtx.resume(); }catch(e){} }
document.addEventListener('pointerdown', unlockAudio, true); document.addEventListener('touchstart', unlockAudio, {passive:true});
function loadVoices(){ const voices=speechSynthesis.getVoices?speechSynthesis.getVoices():[]; voice=voices.find(v=>/es[-_]AR/i.test(v.lang))||voices.find(v=>/^es/i.test(v.lang))||null; }
if('speechSynthesis' in window){ speechSynthesis.onvoiceschanged=loadVoices; setTimeout(loadVoices,500); }
function beep(type){ if(!state.sound) return; try{ unlockAudio(); if(!audioCtx) return; const osc=audioCtx.createOscillator(), gain=audioCtx.createGain(), now=audioCtx.currentTime; osc.connect(gain); gain.connect(audioCtx.destination); const f={deal:300,card:420,win:740,lose:190,call:230,accept:520,reject:160}[type]||380; osc.frequency.setValueAtTime(f,now); gain.gain.setValueAtTime(.001,now); gain.gain.exponentialRampToValueAtTime(.15,now+.02); gain.gain.exponentialRampToValueAtTime(.001,now+.19); osc.start(now); osc.stop(now+.2);}catch(e){} }
function say(t){ if(!state.sound || !('speechSynthesis' in window)) return; try{ speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(t); u.lang='es-AR'; if(voice) u.voice=voice; u.rate=.95; u.pitch=.94; speechSynthesis.speak(u);}catch(e){} }

function clearTimer(){ clearInterval(state.timer); }
function startTimer(){ clearTimer(); if(state.turn!=='player'||state.waiting||state.over){ updateScore(); return; } state.seconds=29; updateScore(); state.timer=setInterval(()=>{ state.seconds--; updateScore(); if(state.seconds<=0){ clearTimer(); if(state.ph.length) playCard(0); } },1000); }
function startMatch(){ goPage('game'); resetMatch(); }
function resetMatch(){ clearTimer(); state.p=0; state.c=0; state.handNo=0; state.over=false; clearLog(); log('Nueva partida iniciada.'); startHand(); }
function startHand(){ clearTimer(); const d=buildDeck(); state.ph=d.slice(0,3); state.ch=d.slice(3,6); state.rounds=[null,null,null]; state.ri=0; state.handNo++; state.mano=state.handNo%2?'player':'cpu'; state.turn=state.mano; state.waiting=false; state.envidoUsed=false; state.florUsed=false; state.trucoValue=1; state.over=false; $('statusText').innerHTML='Nueva mano'; beep('deal'); renderAll(); if(state.turn==='cpu') setTimeout(cpuPlay,800); else startTimer(); }
function playCard(i){ if(state.turn!=='player'||state.waiting||state.over) return; clearTimer(); const c=state.ph.splice(i,1)[0]; state.rounds[state.ri] ||= {}; state.rounds[state.ri].player=c; log(`Jugaste <b>${c.name}</b>.`,'Vos'); beep('card'); state.turn='cpu'; renderAll(); if(state.rounds[state.ri].cpu) setTimeout(resolveRound,400); else setTimeout(cpuPlay,760); }
function cpuPick(){ const current=state.rounds[state.ri]; const opts=state.ch.map((c,i)=>({c,i})); if(current && current.player){ const beat=opts.filter(x=>x.c.r>current.player.r).sort((a,b)=>a.c.r-b.c.r); if(beat.length) return beat[0].i; } return opts.sort((a,b)=>a.c.r-b.c.r)[0].i; }
function cpuPlay(){ if(state.turn!=='cpu'||state.waiting||state.over) return; const idx=cpuPick(); const c=state.ch.splice(idx,1)[0]; state.rounds[state.ri] ||= {}; state.rounds[state.ri].cpu=c; log(`Rival jugó <b>${c.name}</b>.`,'CPU'); beep('card'); state.turn='player'; renderAll(); if(state.rounds[state.ri].player) setTimeout(resolveRound,420); else startTimer(); }
function handWinner(){ const wins=state.rounds.filter(Boolean).map(r=>r.winner); const p=wins.filter(x=>x==='player').length, c=wins.filter(x=>x==='cpu').length; if(p>=2) return 'player'; if(c>=2) return 'cpu'; if(wins.length===2){ if(wins[0]==='parda'&&wins[1]!=='parda') return wins[1]; if(wins[0]!=='parda'&&wins[1]==='parda') return wins[0]; } if(wins.length===3){ if(p>c) return 'player'; if(c>p) return 'cpu'; return state.mano; } return null; }
function resolveRound(){ const r=state.rounds[state.ri]; let w='parda'; if(r.player.r>r.cpu.r) w='player'; else if(r.cpu.r>r.player.r) w='cpu'; r.winner=w; renderSlots(); if(w==='parda'){ log('Mano parda.'); beep('call'); } else if(w==='player'){ log('Ganaste la mano.'); beep('win'); } else { log('El rival ganó la mano.','Sistema'); beep('lose'); }
  const hw=handWinner(); renderAll(); if(hw){ state.over=true; if(hw==='player'){ state.p += state.trucoValue; popupPoints(`+${state.trucoValue} punto${state.trucoValue>1?'s':''}`,`Vos ${state.p} - Rival ${state.c}`,'Ganaste la mano'); log(`Ganaste la mano completa y sumaste ${state.trucoValue}.`); } else { state.c += state.trucoValue; popupPoints(`Rival +${state.trucoValue}`,`Vos ${state.p} - Rival ${state.c}`,'El rival ganó la mano'); log(`El rival ganó la mano completa y sumó ${state.trucoValue}.`,'Sistema'); }
    renderAll(); if(state.p>=state.gameTo||state.c>=state.gameTo){ finishMatch(); return; } setTimeout(startHand,1500); return; }
  state.ri++; state.turn = w==='player'?'player':w==='cpu'?'cpu':state.mano; renderAll(); if(state.turn==='cpu') setTimeout(cpuPlay,760); else startTimer(); }
function singTruco(){ if(state.turn!=='player'||state.waiting||state.over||state.trucoValue>1) return; state.waiting=true; clearTimer(); say('Truco'); beep('call'); log('Cantaste <b>TRUCO</b>.','Vos'); $('statusText').innerHTML='Cantaste <b>TRUCO</b>.'; updateButtons(); setTimeout(()=>{ const power=state.ch.reduce((a,c)=>a+c.r,0); const accept=power>16||Math.random()>.42; if(accept){ state.trucoValue=2; say('Quiero'); beep('accept'); log('Rival dijo <b>quiero</b>.','CPU'); $('statusText').innerHTML='El rival aceptó el <b>TRUCO</b>.'; } else { state.p+=1; say('No quiero'); beep('reject'); log('Rival dijo <b>no quiero</b>. Sumaste 1.','CPU'); popupPoints('+1 punto',`Vos ${state.p} - Rival ${state.c}`,'Truco no querido'); renderAll(); state.waiting=false; if(state.p>=state.gameTo){ finishMatch(); return; } setTimeout(startHand,1300); return; } state.waiting=false; renderAll(); if(state.turn==='player') startTimer(); },920); }
function singEnvido(type){ if(state.turn!=='player'||state.waiting||state.over||state.envidoUsed||state.ri>0) return; state.envidoUsed=true; state.waiting=true; clearTimer(); let label='ENVIDO', pts=2, threshold=23; if(type==='real'){ label='REAL ENVIDO'; pts=3; threshold=26; } if(type==='falta'){ label='FALTA ENVIDO'; pts=Math.max(1,state.gameTo-Math.max(state.p,state.c)); threshold=28; }
  say(label); beep('call'); log(`Cantaste <b>${label}</b>.`,'Vos'); $('statusText').innerHTML=`Cantaste <b>${label}</b>.`; updateButtons(); setTimeout(()=>{ const p=calcEnvido(state.ph), c=calcEnvido(state.ch), accept=c>=threshold||Math.random()>.46; if(accept){ say('Quiero'); beep('accept'); log(`Rival dijo <b>quiero</b>. Tu envido: ${p}. Rival: ${c}.`,'CPU'); if(p>=c){ state.p += pts; popupPoints(`+${pts} punto${pts>1?'s':''}`,`Vos ${state.p} - Rival ${state.c}`,`Ganaste el ${label.toLowerCase()}`); beep('win'); log(`Ganaste el ${label.toLowerCase()} y sumaste ${pts}.`); } else { state.c += pts; popupPoints(`Rival +${pts}`,`Vos ${state.p} - Rival ${state.c}`,`Perdiste el ${label.toLowerCase()}`); beep('lose'); log(`El rival ganó el ${label.toLowerCase()} y sumó ${pts}.`,'Sistema'); } } else { state.p += 1; say('No quiero'); beep('reject'); log('Rival dijo <b>no quiero</b>. Sumaste 1.','CPU'); popupPoints('+1 punto',`Vos ${state.p} - Rival ${state.c}`,`${label} no querido`); }
    state.waiting=false; renderAll(); if(state.p>=state.gameTo||state.c>=state.gameTo){ finishMatch(); return; } if(state.turn==='player') startTimer(); },980); }
function singFlor(){ if(!state.flor||!hasFlor(state.ph)||state.florUsed||state.waiting||state.over||state.ri>0) return; state.florUsed=true; state.waiting=true; clearTimer(); const p=calcFlor(state.ph), rh=hasFlor(state.ch), c=rh?calcFlor(state.ch):0; say('Flor'); beep('call'); log(`Cantaste <b>FLOR</b>. Tenés ${p}.`,'Vos'); $('statusText').innerHTML='Cantaste <b>FLOR</b>.'; setTimeout(()=>{ if(rh){ say('Quiero'); beep('accept'); log(`Rival tiene flor con ${c}.`,'CPU'); if(p>=c){ state.p+=3; popupPoints('+3 puntos',`Vos ${state.p} - Rival ${state.c}`,'Ganaste la flor'); beep('win'); log('Ganaste la flor y sumaste 3.'); } else { state.c+=3; popupPoints('Rival +3',`Vos ${state.p} - Rival ${state.c}`,'Perdiste la flor'); beep('lose'); log('El rival ganó la flor y sumó 3.','Sistema'); } } else { state.p+=3; popupPoints('+3 puntos',`Vos ${state.p} - Rival ${state.c}`,'Flor cantada'); beep('win'); log('Rival no tuvo flor. Sumaste 3.','Sistema'); }
    state.waiting=false; renderAll(); if(state.p>=state.gameTo||state.c>=state.gameTo){ finishMatch(); return; } if(state.turn==='player') startTimer(); },950); }
function goMazo(){ if(state.over) return; clearTimer(); state.c += state.trucoValue; say('Me voy al mazo'); beep('lose'); log(`Te fuiste al mazo. El rival sumó ${state.trucoValue}.`,'Sistema'); popupPoints(`Rival +${state.trucoValue}`,`Vos ${state.p} - Rival ${state.c}`,'Te fuiste al mazo'); renderAll(); if(state.c>=state.gameTo){ finishMatch(); return; } setTimeout(startHand,1400); }
function finishMatch(){ clearTimer(); state.over=true; $('modalTitle').textContent = state.p>=state.gameTo ? '¡Ganaste la partida!' : 'Ganó el rival'; $('modalText').textContent = `Resultado final: Vos ${state.p} - Rival ${state.c}.`; $('endModal').classList.add('active'); }
function closeModal(){ $('endModal').classList.remove('active'); }

function renderTables(){ const data=[{name:'IA Maestro',type:'IA',cost:'Gratis',prize:'Práctica',desc:'Entrá directo a jugar contra la computadora.'},{name:'Mesa Pública 1v1',type:'Pública',cost:'Gratis',prize:'Sin premio',desc:'Partida rápida abierta para todos.'},{name:'Mesa Free Federal',type:'Pública',cost:'Gratis',prize:'XP y ranking',desc:'Suma puntos demo al ranking.'},{name:'Privada TP-7K2',type:'Privada',cost:'Gratis',prize:'Amigos',desc:'Sala por código para invitados.'},{name:'Sala VIP Obelisco',type:'VIP',cost:'$5.000',prize:'Premio demo',desc:'Mesa premium con ambientación exclusiva.'},{name:'Copa Exprés',type:'Pública',cost:'$2.000',prize:'$20.000 demo',desc:'Mesa con pozo y premio demo.'}]; const q=$('searchTables').value.toLowerCase().trim(); const f=$('filterTables').value; const fil=data.filter(t=>(f==='Todas'||t.type===f)&&(`${t.name} ${t.type} ${t.desc}`.toLowerCase().includes(q))); $('tableGrid').innerHTML=fil.map(t=>`<div class="table-card"><div class="head"><div><h3>${t.name}</h3><p>${t.desc}</p></div><span class="tag">${t.type}</span></div><div class="meta"><span class="tag">Costo: ${t.cost}</span><span class="tag">${t.prize}</span></div><button class="btn ${t.type==='IA'?'primary':'secondary'}" onclick="${t.type==='IA'?'startMatch()':'toast(\'Ingreso demo a '+t.name.replace(/'/g,'')+'\')'}">${t.type==='IA'?'Jugar':'Entrar'}</button></div>`).join(''); }
function renderTours(){ const tours=[['Torneo Relámpago','21:00','Gratis','Insignia Pro'],['Copa TrucoPro AR','22:30','$1.500','$75.000 demo'],['Duplas Federales','23:15','$2.000','$120.000 demo']]; $('tourGrid').innerHTML=tours.map(t=>`<div class="tour-card"><h3>🏆 ${t[0]}</h3><p>Horario: <b>${t[1]}</b></p><p>Entrada: <b>${t[2]}</b></p><p>Premio: <b>${t[3]}</b></p><button class="btn primary" onclick="toast('Inscripción demo realizada')">Inscribirme</button></div>`).join(''); }
function renderRanking(){ const rows=[[1,'ReyEspada',8840,'78%'],[2,'Mati7Oros',8120,'74%'],[3,'DanielPro',7905,'72%'],[4,'SofiAR',7340,'69%'],[5,'NicoBastos',7012,'66%']]; $('rankGrid').innerHTML=rows.map(r=>`<div class="rank-row"><span>#${r[0]}</span><span>${r[1]}</span><span>${r[2]} pts</span><span>${r[3]}</span></div>`).join(''); }
function renderHero(){ const cards=[{n:12,s:'copa',name:'Rey de Copas'},{n:7,s:'oro',name:'Siete de Oros'},{n:11,s:'basto',name:'Caballo de Bastos'}]; $('heroCards').innerHTML=cards.map(cardHTML).join(''); }
function sendGlobal(){ const i=$('globalInput'); const v=i.value.trim(); if(!v) return; const d=document.createElement('div'); d.innerHTML=`<b>Vos:</b> ${v}`; $('globalChat').appendChild(d); i.value=''; }
function sendRival(){ const i=$('chatRivalInput'); const v=i.value.trim(); if(!v) return; const d=document.createElement('div'); d.innerHTML=`<b>Vos:</b> ${v}`; $('chatRival').appendChild(d); i.value=''; setTimeout(()=>{ const r=document.createElement('div'); r.innerHTML='<b>CPU:</b> Buena jugada.'; $('chatRival').appendChild(r); },700); }
function saveSettings(){ state.flor=$('toggleFlor').classList.contains('on'); state.sound=$('toggleSound').classList.contains('on'); state.gameTo=Number($('selectPoints').value); renderAll(); toast('Configuración guardada'); }

$('btnPlayNow').onclick=startMatch; $('btnHeroPlay').onclick=startMatch; $('btnNewHand').onclick=startHand; $('btnReset').onclick=resetMatch; $('btnTruco').onclick=singTruco; $('btnEnvido').onclick=()=>singEnvido('simple'); $('btnReal').onclick=()=>singEnvido('real'); $('btnFalta').onclick=()=>singEnvido('falta'); $('btnFlor').onclick=singFlor; $('btnMazo').onclick=goMazo; $('btnSound').onclick=()=>{ state.sound=!state.sound; setToggle($('toggleSound'),state.sound); renderAll(); toast(state.sound?'Sonido activado':'Sonido desactivado'); if(state.sound) say('Sonido activado'); }; $('btnReplay').onclick=()=>{ closeModal(); resetMatch(); goPage('game'); }; $('btnCloseModal').onclick=closeModal; $('btnPrivate').onclick=()=>toast('Mesa privada creada: TP-'+Math.random().toString(36).slice(2,6).toUpperCase()); $('searchTables').addEventListener('input',renderTables); $('filterTables').addEventListener('change',renderTables); $('btnSendGlobal').onclick=sendGlobal; $('btnSendRival').onclick=sendRival; $('toggleFlor').onclick=()=>setToggle($('toggleFlor'),!$('toggleFlor').classList.contains('on')); $('toggleSound').onclick=()=>setToggle($('toggleSound'),!$('toggleSound').classList.contains('on')); $('btnSaveSettings').onclick=saveSettings;

renderHero(); renderTables(); renderTours(); renderRanking(); renderAll(); clearLog(); log('Partida lista para jugar.');
